# Generated by Django 3.0.4 on 2020-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200323_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10),
        ),
    ]
