# Generated by Django 3.0.4 on 2020-06-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200611_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmessage',
            old_name='message',
            new_name='messagess',
        ),
    ]
