# Generated by Django 3.0.4 on 2020-06-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200611_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='kimden',
            field=models.CharField(default='Admin', max_length=30),
        ),
    ]
