# Generated by Django 3.0.4 on 2020-06-11 16:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_adminmessage_kimden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='messagess',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
