# Generated by Django 3.0.4 on 2020-06-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200611_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='sifreunuttum',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
