# Generated by Django 3.0.4 on 2020-05-26 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turistikmekan', '0015_auto_20200526_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='guidecategory',
        ),
    ]
