# Generated by Django 3.0.4 on 2020-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistikmekan', '0016_remove_product_guidecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='guidecategory',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
