# Generated by Django 3.0.4 on 2020-05-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turistikmekan', '0018_auto_20200526_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='guidecategory',
        ),
    ]
