# Generated by Django 3.0.4 on 2020-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistikmekan', '0021_auto_20200607_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'Evet'), ('False', 'Hayır')], default='True', max_length=10),
        ),
    ]
