# Generated by Django 3.0.4 on 2020-06-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistikmekan', '0024_product_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='where',
            field=models.CharField(blank=True, choices=[('Yurtici', 'Yurtiçi'), ('Yurtdisi', 'YurdDışı')], max_length=15),
        ),
    ]
