# Generated by Django 3.0.4 on 2020-06-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turistikmekan', '0027_auto_20200610_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
