# Generated by Django 3.0.4 on 2020-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistikmekan', '0028_remove_comment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='howtogo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
