# Generated by Django 3.0.4 on 2020-05-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200520_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='aa.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
