# Generated by Django 3.0.4 on 2020-05-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_commentcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentcontent',
        ),
    ]
